version: '3.7'
services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
    - '3306:3306'
    volumes:
    - ./data:/docker-entrypoint-initdb.d
    environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_DATABASE=database
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password


#    set DB_URL=jdbc:mysql://localhost:3306/database
#    set DB_USER=user
#    set DB_PASS=password